### ISSUE TITLE
Unified (Managed) Memory Support

### ISSUE THREAD

**Issue by TheP4Thetic** [ROCm/HIP#2033]
Is unified memory management in HIP supported? You said in https://github.com/ROCm-Developer-Tools/HIP/blob/master/docs/markdown/hip_faq.md that managed memory is not supported yet, otherwise in HIP/src/hip_memory.cpp the function hipMallocManaged() is implemented. If I use hipMallocManaged() in my program, the performance drops down a lot. Thanks for your answer!

How differs hipMallocManaged() from cudaMallocManaged()?

**Comment by illuhad** [comment]
Not an AMD dev, but my understanding is that it's currently implemented with zero copy memory, i.e. if you use it all memory accesses go through PCIe, which is of course slow for memory-intensive use cases. I don't know whether the lack of a page migration-based solution is due to hardware limitations or just missing from the software side, but I would be interested in that feature as well. Maybe someone from AMD can comment?

**Comment by ppanchad-amd** [comment]
@TheP4Thetic Apologies for the lack of response.  Do you still require assistance for this ticket? Thanks!

**Comment by ppanchad-amd** [comment]
@TheP4Thetic Closing ticket. Please re-open if you still need assistance with this ticket. Thanks!
