### ISSUE TITLE
HIP - OpenGL/Vulkan Interoperability Status and Plans

### ISSUE THREAD

**Issue by FilipVaverka** [ROCm/HIP#2237]
What is the current status and future plans for interoperability between HIP (and OpenCL) and graphics APIs like OpenGL or Vulkan running on top of Mesa?

So far HIP doesn't seem to expose this functionality at all, while OpenCL (ROCm 4.0.0 distribution) does expose it, but doesn't work for me (OpenCL <-> OpenGL buffer sharing leads to GPU page faults).

Are there any plans to introduce this functionality and other APIs such as [External Resource Interoperability](https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__EXTRES__INTEROP.html) to allow external data sharing and synchronization?

**Comment by Nulled-Out** [comment]
Also curious about this, I was under the impression that OpenCL was to converge with Vulkan Interop?

**Comment by masahi** [comment]
There is already an example of vk interop: https://github.com/ROCm-Developer-Tools/HIP/pull/2375

**Comment by FilipVaverka** [comment]
So I've tried to build the example on Linux against ROCm 4.5.0 and I'm getting "Segmentation fault" in "hipImportExternalMemory" in libamdhip64.so. Which Vulkan runtimes are supported? (here I used opensource RADV)
The example needed little bit of tweaking to compile on Linux as it seems to be aimed at Windows (is there even Windows support in ROCm?).

**Comment by masahi** [comment]
Yeah, rocm on windows is becoming a thing now https://code.blender.org/2021/11/next-level-support-for-amd-gpus/

**Comment by FilipVaverka** [comment]
Yes, I was bit surprised seeing that as I haven't seen any information on how to setup ROCm dev. tools on Windows yet.

**Comment by ppanchad-amd** [comment]
@FilipVaverka Can you please test with the latest ROCm 6.1.2? If resolved, please close the ticket. Thanks!

**Comment by sohaibnd** [comment]
Hi @FilipVaverka, the HIP + Vulkan interop example that @masahi is referring to is meant for Windows. While the entire ROCm stack is not supported on windows, there has been support for HIP for a while, and this had been recently extended with the announcement of HIP SDK for Windows (here is the [documentation](https://rocm.docs.amd.com/projects/install-on-windows/en/latest/)). 

On Linux, HIP interoperability with Vulkan external semaphores is not supported (see [documentation](https://rocm.docs.amd.com/projects/HIP/en/latest/doxygen/html/group___external.html)) so that example will not work.

However, there are some supported functions for HIP + OpenGL interop documented [here](https://rocm.docs.amd.com/projects/HIP/en/latest/reference/hip_runtime_api/modules/opengl_interoperability.html#opengl-interoperability-reference) which should work on both Windows and Linux.

Please let me know if you need anything else!

**Comment by sohaibnd** [comment]
@FilipVaverka I'm going to close this issue due to inactivity. If you have any other questions about interop support, feel free to re-open this issue.
