### ISSUE TITLE
Drastic difference in execution time between CUDA and HIP versions of the same code

### ISSUE THREAD

**Issue by PhilipDeegan** [ROCm/HIP#2240]
Hi there,

I've tried running this: https://www.particleincell.com/wp-content/uploads/2016/02/sheath-gpu.cu
reference: https://www.particleincell.com/2016/cuda-pic
On AMD Radeon RX Vega 64, and a Nvidia 1080 Max-Q, 

AMD
```
Found GPU 'Device 687f' with 8176 Gb of global memory, max 1024 threads per block, and 64
multiprocessors
TS:25  np_i:500000  np_e:500000  dphi:1.4
TS:50  np_i:500000  np_e:500000  dphi:4.17
TS:75  np_i:500000  np_e:500000  dphi:5.82
TS:100  np_i:500000  np_e:500000  dphi:5.02
TS:125  np_i:500000  np_e:500000  dphi:4.06

...

TS:9925  np_i:500000  np_e:500000  dphi:6.85
TS:9950  np_i:500000  np_e:500000  dphi:5.66
TS:9975  np_i:500000  np_e:500000  dphi:5.46
TS:10000  np_i:500000  np_e:500000  dphi:5.42
Time per time step: 155 ms
```

Nvidia
```
Found GPU 'GeForce GTX 1080 with Max-Q Design' with 8114.44 Gb of global memory, max 1024 threads
per block, and 20 multiprocessors
TS:25  np_i:500000  np_e:500000  dphi:1.38
TS:50  np_i:500000  np_e:500000  dphi:4.19
TS:75  np_i:500000  np_e:500000  dphi:5.93
TS:100  np_i:500000  np_e:500000 dphi:5.05
TS:125  np_i:500000  np_e:500000  dphi:4.04

...

TS:9925  np_i:500000  np_e:500000  dphi:6.85
TS:9950  np_i:500000  np_e:500000  dphi:5.77
TS:9975  np_i:500000  np_e:500000  dphi:5.41
TS:10000  np_i:500000  np_e:500000  dphi:5.4
Time per time step: 4.32 ms
```

both versions which are as identical as can be can be found here:
https://github.com/PhilipDeegan/PHARE/blob/gpu/tools/hw/gpu/bench/sheath-gpu.hip.cpp
https://github.com/PhilipDeegan/PHARE/blob/gpu/tools/hw/gpu/bench/sheath-gpu.cuda.cpp

**Comment by PhilipDeegan** [comment]
I should add the RX Vega testing was done inside docker so the comparisons are not exactly identical

RX Vega machine: 
CPU: AMD Ryzen 9 3950X 16-Core Processor
Host OS: Debian GNU/Linux bullseye/sid
Kernel: Linux fad 5.10.0-3-amd64 #1 SMP Debian 5.10.13-1 (2021-02-06) x86_64 GNU/Linux
Container OS: Ubuntu 20.04.2 LTS

1080 Max-Q machine
CPU: Intel(R) Core(TM) i7-7820HK CPU @ 2.90GHz
Host OS: Ubuntu 20.04.2 LTS
KernelLinux feh 5.8.0-44-generic #50~20.04.1-Ubuntu SMP Wed Feb 10 21:07:30 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by gandryey** [comment]
Try 256 threads per block. In general you have to profile each kernel and report the slowest to the compiler.

**Comment by PhilipDeegan** [comment]
it's already configured to 256 threads per block

https://github.com/PhilipDeegan/PHARE/blob/gpu/tools/hw/gpu/bench/sheath-gpu.hip.cpp#L51

**Comment by gandryey** [comment]
Use rocprofiler (--hip-trace option), it should produce JSON compatible with chrome://tracing. Then identify where runtime/HW spends the most of time.

**Comment by zjin-lcf** [comment]
If there is a MI100 GPU, please give it a try.  Hope this helps.

**Comment by zjin-lcf** [comment]
Thank you for the example. I could reproduce the performance issue. If there is a MI100 GPU, please give it a try.

**Comment by ppanchad-amd** [comment]
@PhilipDeegan, Sorry for the lack of response. Please try latest ROCm 6.0.2 (HIP 6.0.32831) to see if your issue still exists? If resolved, please close the ticket. Thanks.

**Comment by PhilipDeegan** [comment]
I only have a gaming AMD GPU atm so I cant' really test this any more

but,  on my 6900XT, it's like `Time per time step: 337 ms` on ROCm 6.0.2

**Comment by ppanchad-amd** [comment]
@PhilipDeegan Thanks! Internal ticket has been created to investigate this issue.

**Comment by jamesxu2** [comment]
Hello @PhilipDeegan , I was able to reproduce your issue, and identify that the bottleneck in the HIP code is the atomicAdd() inside your dev_scatter kernel. By default, the HIP compiler will use a slower atomic CAS loop instead of a (potentially unsafe) hardware atomic add, whereas CUDA does not make this distinction and uses a fast atomicAdd instruction only. For reference, see [the docs on atomicAdd](https://rocm.docs.amd.com/projects/HIP/en/latest/reference/kernel_language.html#unsafe-floating-point-atomic-rmw-operations).

In particular:
> The HIP-Clang compiler offers a compile-time option, so you can choose fast–but potentially unsafe–atomic instructions for your code. On devices that support these instructions, you can include the -munsafe-fp-atomics option. This flag indicates to the compiler that all floating-point atomic function calls are allowed to use an unsafe version, if one exists. For example, on some devices, this flag indicates to the compiler that no floating-point atomicAdd function can target fine-grained memory.

 I recognize the explanation provided in the rest of this section may be unsatisfying, and we're working on improving it. 

The solution to this is to pass the **-munsafe-fp-atomics** flag to the compiler to force it to use hardware atomicAdds. On my system, this reduces the time per timestep on my RX7900 to 3.6s, comparable to the CUDA runtime on an RTX4090. 

However, I recommend that with this (and other programs) to validate the results of your computation using known reference values if possible to ensure the correctness of your program when ported to GPU. (See: [CUDA best practices](https://docs.nvidia.com/cuda/cuda-c-best-practices-guide/#reference-comparison))

Let me know if this fixes your problem or if you have any other questions.

**Comment by PhilipDeegan** [comment]
@jamesxu2 I actually only came across unsafe atomics last week, so this fits nicely

> I recognize the explanation provided in the rest of this section may be unsatisfying, and we're working on improving it.

all good, I don't mind having a direct call to the unsafe functions for certain contexts

**Comment by jamesxu2** [comment]
Great! I'll be closing this ticket, but feel free to reopen it if your issue isn't resolved.
