### ISSUE TITLE
HIP support ARM64 Linux as same as ROCm supported ARM64

### ISSUE THREAD

**Issue by wormwang** [ROCm/HIP#597]
I find https://rocm.github.io/ROCmRadeonProcompare.html supported ARM64 CPU, like ARM AArch64 /Cavium Tunder X.

How and which version of HIP support ARM64 Linux?

**Comment by gstoner** [comment]
We had it running with 1.6.4

**Comment by wormwang** [comment]
I found HIP just have roc-1.6.0? how to checkout 1.6.4?

**Comment by YJessicaGao** [comment]
@wormwang  
Hi, have you successfully built hip version 2.0.0(or other version) or only 1.6.0 on ARM64 linux?
Cause I saw you have built MIOPEN, but mine reports an error, says, cannot find -lhip::device. I guess the reason is hip::device is not defined in hip 1.6.0.
It will really help if you could reply. Thanks.

**Comment by nartmada** [comment]
Hi @wormwang, apologies for the lack of response. Can you please check latest ROCm 6.0.2 (HIP 6.0.32831) to see if your query has been addressed? Thanks.
