### ISSUE TITLE
atomicInc doesn't work on host accessible mapped memory (hipHostMalloc)

### ISSUE THREAD

**Issue by x3ccd4828** [ROCm/HIP#815]
It seems that atomicInc doesn't actually increment the value the specified mapped memory.
I checked the tests folder in hip and there is no test that covers this scenario. 
There is a scenario to test hipHostMalloc but without atomic functions, and there is an atomicInc test but it doesn't use mapped memory.

**Comment by gargrahul** [comment]
@x3ccd4828 Could you please share an example code?

**Comment by x3ccd4828** [comment]
@gargrahul I don't have the exact testcase I used back in December, but I modified the hipSimpleAtomicsTest.cpp (tests/src/deviceLib/hipSimpleAtomicsTest.cpp) inside this repository.

I have attached the patch file which adds host accessible mapped memory.

[atomicInc_test_with_hipHostmalloc.txt](https://github.com/ROCm-Developer-Tools/HIP/files/3114010/atomicInc_test_with_hipHostmalloc.txt)

**Comment by gargrahul** [comment]
@x3ccd4828 Could you please try using atomicAdd instead ? There is a known limitation with atomicInc when PCIe is crossed.

**Comment by x3ccd4828** [comment]
AtomicAdd works but the CUDA code I was porting over used atomicInc and it was very frustrating debugging the code to root case the fact that atomicInc doesn't work. 

Can it at least be added to documantation that it is broken and it should not be used? Also keep this issue open until it is fixed.

**Comment by b-sumner** [comment]
The documentation does need to be improved, and wasting your time is certainly not something we want to do.

When crossing the PCIe bus, we are limited to what PCIe provides and your what your system hardware actually supports.  Some systems claim to support PCIe atomics but don't manage to end-to-end because one of the components doesn't.  But even when fully supported, PCIe itself does not define an atomic increment operation that wraps at a specified index  When PCIe atomics are available, a compare and swap (CAS) operation is available which can be used to implement the wrapping increment semantics, however if the wraparound point is a power of two, then we can just ignore the upper bits.

The HIP headers could be changed to implement atomicInc using CAS, but this would heavily penalize every atomicInc that does not cross PCIe.   We don't know at compile time whether PCIe is crossed, and any runtime test (and I'm not sure one is possible) would also be expensive.  It doesn't seem likely that there is a fix to this issue that will satisfy all developers.  Given this @x3ccd4828 would documentation improvements be sufficient for closing this issue?

**Comment by x3ccd4828** [comment]
@b-sumner the documantation improvements would work to close this issue.

**Comment by nartmada** [comment]
Hi @x3ccd4828, sorry for the lack of response.  Is the documentation sufficient enough for you to close the ticket?  Thanks.

**Comment by x3ccd4828** [comment]
It's been a few years, I will close it.
