### ISSUE TITLE
Information about JIT compilation and plan to implement culink*-like API

### ISSUE THREAD

**Issue by kazulittlefox** [ROCm/HIP#906]
Hello.

I have intended to convert Cuda project using JIT compiler and culink API.
But there is no culink-like API in HIP, and there would be found neither information 
about JIT compilation on HIP, nor plan to implement JIT compilation.

I would like to know whether HIP(and their compliers) achive JIT compilation interface,
and know there will be any plan for implementing culink-like APIs.

Thanks in advance.

**Comment by ArturoBlas** [comment]
I would also be interested where support for this stands at the moment please.

**Comment by nartmada** [comment]
Hi @kazulittlefox, apologies for the lack of response.  Do you still need assistance with this ticket?  Thanks.

**Comment by ArturoBlas** [comment]
> Hi @kazulittlefox, apologies for the lack of response. Do you still need assistance with this ticket? Thanks.

I would also be interested to know what’s the current state of runtime linking and LTO with HIP/ROCm on both Linux and Windows.
Thank you.

**Comment by ppanchad-amd** [comment]
@ArturoBlas I will check with the internal team and will get back to you. Thanks!

**Comment by tcgu-amd** [comment]
@ArturoBlas and @kazulittlefox Thanks for reaching out and sorry for the lack of responses. Runtime compilation is supported via HIP RTC and runtime linking has been supported since ROCm 5.6.0x. https://github.com/ROCm/clr/blob/rocm-5.6.x/hipamd/src/hiprtc/hiprtc.cpp#L273. Thanks! 

I will be closing this issue for now since I believe the above answers the original question. However, please feel free to ask follow up questions @ArturoBlas if you are curious about specific API support. Thank you!
